# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/SoutheastUniversity/mulclock_final/mulclock.cache/wt [current_project]
set_property parent.project_path D:/SoutheastUniversity/mulclock_final/mulclock.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/SoutheastUniversity/mulclock_final/mulclock.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/SoutheastUniversity/mulclock_final/mulclock.srcs/sources_1/new/counter_sync_r.v
  D:/SoutheastUniversity/mulclock_final/mulclock.srcs/sources_1/new/days_per_month.v
  D:/SoutheastUniversity/mulclock_final/mulclock.srcs/sources_1/new/disp_dec.v
  D:/SoutheastUniversity/mulclock_final/mulclock.srcs/sources_1/new/dual_hex.v
  D:/SoutheastUniversity/mulclock_final/mulclock.srcs/sources_1/new/int_div.v
  D:/SoutheastUniversity/mulclock_final/mulclock.srcs/sources_1/new/myclock.v
  D:/SoutheastUniversity/mulclock_final/mulclock.srcs/sources_1/new/seg_decoder.v
  D:/SoutheastUniversity/mulclock_final/mulclock.srcs/sources_1/new/clock.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/SoutheastUniversity/mulclock_final/mulclock.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files D:/SoutheastUniversity/mulclock_final/mulclock.srcs/constrs_1/new/constraints.xdc]


synth_design -top clock -part xc7a100tcsg324-1


write_checkpoint -force -noxdef clock.dcp

catch { report_utilization -file clock_utilization_synth.rpt -pb clock_utilization_synth.pb }
